Competition
semanadeinformatica/website-2020 pull request #9
Opened 2020-10-05 14:24 UTC by MPDR200011

# Description

Page for the programming competition, just a change in the order of elements. Was going to create this PR only when we had the new data, but since other pages are being added without content I decided to create the PR for the page now and add the new content later.

# Tasks

- [x] Change the layout
- [x] Fix spacings
- [ ] Add new regulation text
- [ ] Add new prize information
- [ ] Add new hackerank link

2020-10-05 14:35 UTC, andrefmrocha approved these changes
Lgtm but there is many commits here that have no value whatsoever. Might we squash all of these commits on merge?

2020-10-05 14:37 UTC, andrefmrocha requested changes
In mobile this happens: 
![image](https://user-images.githubusercontent.com/33755974/95093305-89f7d300-0720-11eb-9e42-82a98c3a4fd9.png)

Shouldn't all of the prizes to show in the yellow section?

2020-10-06 13:46 UTC, MPDR200011 commented
> Shouldn't all of the prizes to show in the yellow section?

In that case I copied the behavior of what happened in last year's version of the page.

![image](https://user-images.githubusercontent.com/4912677/95209773-a1979000-07e2-11eb-9d58-e81b335e3884.png)

I can change it if required.

2020-10-06 14:05 UTC, MPDR200011 commented
> Lgtm but there is many commits here that have no value whatsoever. Might we squash all of these commits on merge?

Yes, we can do this.

2020-10-06 14:23 UTC, pedromsfernandes requested changes

2020-10-06 14:23 UTC, pedromsfernandes commented on src/pages/competicao-programacao.js
>    <Layout>
Should be a dark footer

2020-10-07 09:31 UTC, andrefmrocha approved these changes, later dismissed
:ship:

2020-10-07 10:42 UTC, pedromsfernandes approved these changes, later dismissed

2020-10-08 14:04 UTC, SantosAntero commented
Everything looks fine, but I would like to point out that the "Participar" button seems really small compared with the bar and the mockups, I don't know if this is something that I didn't notice before or if some change affected this. I understand this can be considered a bit of scope creep 👀 but since everything else is fine I don't think it would be that bad if we fixed that in this PR.

2020-10-08 15:03 UTC, MPDR200011 commented
Ok, I updated the participate button style to be bigger. I also added the text that I completely forgot to add.

2020-10-08 15:07 UTC, andrefmrocha approved these changes, later dismissed
Thanks @SantosAntero !

2020-10-08 20:52 UTC, MPDR200011 commented
I went ahead and also added a breakpoint to the button as it was becoming deformatted on smaller screens.

2020-10-08 21:03 UTC, pedromsfernandes approved these changes

2020-10-08 21:15 UTC, SantosAntero approved these changes
Looks good!

2020-10-08 21:15 UTC, merged